package org.ferdidrgn.hudaquran.domain.model

data class EsmaName(val arabic: String, val name: String, val meaning: String)

val esmaulHusna = listOf(
    EsmaName("الله", "Allah", "Eşi ve benzeri olmayan tek ilah"),
    EsmaName("الرحمن", "Er-Rahman", "Dünyada tüm varlıklara merhamet eden"),
    EsmaName("الرحيم", "Er-Rahim", "Ahirette müminlere merhamet eden"),
    EsmaName("الملك", "El-Melik", "Mülkün ve kâinatın gerçek sahibi"),
    EsmaName("القدوس", "El-Kuddüs", "Her türlü eksiklikten uzak"),
    EsmaName("السلام", "Es-Selam", "Selamet ve esenlik veren"),
    EsmaName("المؤمن", "El-Mü'min", "Güven ve emniyet veren"),
    EsmaName("المهيمن", "El-Müheymin", "Her şeyi gözetip koruyan"),
    EsmaName("العزيز", "El-Aziz", "Yüce ve daima galip olan"),
    EsmaName("الجبار", "El-Cebbar", "Dilediğini yaptırmaya gücü yeten"),
    EsmaName("المتكبر", "El-Mütekebbir", "Büyüklükte eşi olmayan"),
    EsmaName("الخالق", "El-Halık", "Yoktan yaratan"),
    EsmaName("البارئ", "El-Bari", "Kusursuz ve uyumlu yaratan"),
    EsmaName("المصور", "El-Musavvir", "Varlıklara şekil veren"),
    EsmaName("الغفار", "El-Gaffar", "Günahları çokça bağışlayan"),
    EsmaName("القهار", "El-Kahhar", "Her şeye galip gelen"),
    EsmaName("الوهاب", "El-Vehhab", "Karşılıksız bol bol bağışlayan"),
    EsmaName("الرزاق", "Er-Rezzak", "Bütün canlılara rızık veren"),
    EsmaName("الفتاح", "El-Fettah", "Müşkülleri çözüp kolaylaştıran"),
    EsmaName("العليم", "El-Alim", "Her şeyi hakkıyla bilen"),
    EsmaName("القابض", "El-Kabıd", "Rızkı ve canı dilediğince daraltan"),
    EsmaName("الباسط", "El-Basıt", "Rızkı dilediğince genişleten"),
    EsmaName("الخافض", "El-Hafıd", "Dilediğini alçaltan"),
    EsmaName("الرافع", "Er-Rafi'", "Dilediğini yücelten"),
    EsmaName("المعز", "El-Muizz", "Dilediğine izzet veren"),
    EsmaName("المذل", "El-Müzil", "Dilediğini zillete düşüren"),
    EsmaName("السميع", "Es-Semi'", "Her şeyi işiten"),
    EsmaName("البصير", "El-Basir", "Her şeyi gören"),
    EsmaName("الحكم", "El-Hakem", "Hak ile hükmeden"),
    EsmaName("العدل", "El-Adl", "Sonsuz adalet sahibi"),
    EsmaName("اللطيف", "El-Latif", "Kullarına çok lütufkâr olan"),
    EsmaName("الخبير", "El-Habir", "Her şeyden haberdar olan"),
    EsmaName("الحليم", "El-Halim", "Yumuşak davranan, hilm sahibi"),
    EsmaName("العظيم", "El-Azim", "Sonsuz büyüklük sahibi"),
    EsmaName("الغفور", "El-Gafur", "Çok bağışlayan"),
    EsmaName("الشكور", "Eş-Şekur", "İyiliğe kat kat karşılık veren"),
    EsmaName("العلي", "El-Aliyy", "Şanı çok yüce olan"),
    EsmaName("الكبير", "El-Kebir", "Büyüklükte eşi olmayan"),
    EsmaName("الحفيظ", "El-Hafiz", "Her şeyi koruyup gözeten"),
    EsmaName("المقيت", "El-Mukit", "Yarattıklarını rızıklandıran"),
    EsmaName("الحسيب", "El-Hasib", "Herkesin hesabını gören"),
    EsmaName("الجليل", "El-Celil", "Celal ve azamet sahibi"),
    EsmaName("الكريم", "El-Kerim", "Sonsuz cömertlik sahibi"),
    EsmaName("الرقيب", "Er-Rakib", "Her şeyi gözetleyen"),
    EsmaName("المجيب", "El-Mucib", "Duaları kabul eden"),
    EsmaName("الواسع", "El-Vasi'", "İlmi ve rahmeti sınırsız olan"),
    EsmaName("الحكيم", "El-Hakim", "Her işi hikmetli olan"),
    EsmaName("الودود", "El-Vedud", "Kullarını çok seven, sevilen"),
    EsmaName("المجيد", "El-Mecid", "Şanı ve şerefi yüce olan"),
    EsmaName("الباعث", "El-Ba'is", "Ölüleri diriltip yeniden gönderen"),
    EsmaName("الشهيد", "Eş-Şehid", "Her şeye şahit olan"),
    EsmaName("الحق", "El-Hakk", "Varlığı ve sözü gerçek olan"),
    EsmaName("الوكيل", "El-Vekil", "Kendisine tevekkül edilen"),
    EsmaName("القوي", "El-Kaviyy", "Sonsuz kudret sahibi"),
    EsmaName("المتين", "El-Metin", "Kuvveti sağlam ve sarsılmaz olan"),
    EsmaName("الولي", "El-Veliyy", "Müminlerin dostu ve yardımcısı"),
    EsmaName("الحميد", "El-Hamid", "Bütün övgülere layık olan"),
    EsmaName("المحصي", "El-Muhsi", "Her şeyin sayısını bilen"),
    EsmaName("المبدئ", "El-Mübdi'", "Varlıkları örneksiz yoktan yaratan"),
    EsmaName("المعيد", "El-Muid", "Yarattıklarını tekrar var eden"),
    EsmaName("المحيي", "El-Muhyi", "Can veren, dirilten"),
    EsmaName("المميت", "El-Mümit", "Ölümü yaratan"),
    EsmaName("الحي", "El-Hayy", "Ezelî ve ebedî diri olan"),
    EsmaName("القيوم", "El-Kayyum", "Her şeyi ayakta tutan"),
    EsmaName("الواجد", "El-Vacid", "Dilediğini dilediği an bulan"),
    EsmaName("الماجد", "El-Macid", "Şanı ve kerem sahibi büyük olan"),
    EsmaName("الواحد", "El-Vahid", "Zatında, sıfatlarında tek olan"),
    EsmaName("الصمد", "Es-Samed", "Her şeyin kendisine muhtaç olduğu"),
    EsmaName("القادر", "El-Kadir", "Sonsuz güç ve kudret sahibi"),
    EsmaName("المقتدر", "El-Muktedir", "Dilediği şeyi dilediği gibi yapan"),
    EsmaName("المقدم", "El-Mukaddim", "Dilediğini öne alan"),
    EsmaName("المؤخر", "El-Muahhir", "Dilediğini geri bırakan"),
    EsmaName("الأول", "El-Evvel", "Varlığının başlangıcı olmayan"),
    EsmaName("الآخر", "El-Ahir", "Varlığının sonu olmayan"),
    EsmaName("الظاهر", "Ez-Zahir", "Varlığı apaçık delillerle bilinen"),
    EsmaName("الباطن", "El-Batın", "Zatının hakikati akılla kavranamayan"),
    EsmaName("الوالي", "El-Vali", "Bütün kâinatı yöneten"),
    EsmaName("المتعالي", "El-Müteali", "Akıl ve hayalin erişemeyeceği kadar yüce"),
    EsmaName("البر", "El-Berr", "İyilik ve ihsanı bol olan"),
    EsmaName("التواب", "Et-Tevvab", "Tövbeleri kabul edip bağışlayan"),
    EsmaName("المنتقم", "El-Müntekim", "Suçluyu adaletle cezalandıran"),
    EsmaName("العفو", "El-Afüvv", "Günahları affeden"),
    EsmaName("الرؤوف", "Er-Rauf", "Çok şefkatli ve merhametli olan"),
    EsmaName("مالك الملك", "Malikü'l-Mülk", "Mülkün gerçek ve tek sahibi"),
    EsmaName("ذو الجلال والإكرام", "Zülcelali vel-İkram", "Azamet ve ikram sahibi"),
    EsmaName("المقسط", "El-Muksit", "Her işi denk ve adaletli yapan"),
    EsmaName("الجامع", "El-Cami'", "Dilediğini dilediği yerde toplayan"),
    EsmaName("الغني", "El-Ganiyy", "Hiçbir şeye muhtaç olmayan"),
    EsmaName("المغني", "El-Muğni", "Dilediğini zengin kılan"),
    EsmaName("المانع", "El-Mani'", "İstemediği şeye engel olan"),
    EsmaName("الضار", "Ed-Darr", "Zarar verecek şeyleri yaratan"),
    EsmaName("النافع", "En-Nafi'", "Fayda verecek şeyleri yaratan"),
    EsmaName("النور", "En-Nur", "Âlemleri nurlandıran"),
    EsmaName("الهادي", "El-Hadi", "Kullarını doğru yola ileten"),
    EsmaName("البديع", "El-Bedi'", "Eşi ve benzeri olmadan yaratan"),
    EsmaName("الباقي", "El-Baki", "Varlığının sonu olmayan"),
    EsmaName("الوارث", "El-Varis", "Her şeyin gerçek ve son varisi"),
    EsmaName("الرشيد", "Er-Reşid", "Her işi doğru bir düzen üzere yürüten"),
    EsmaName("الصبور", "Es-Sabur", "Çok sabırlı olan"),
)
